import { type NextPage } from 'next'
import Head from 'next/head'

import Input from '../../components/atoms/Input'
import Button from 'components/atoms/Button'
import ThemeChanger from 'components/atoms/ThemeChanger'
import Select from 'components/atoms/Select'
import Table from 'components/atoms/Table'
import NavBar2 from 'components/organism/Navbar'

const Home: NextPage = () => {
  const options = ['hello', 'world']

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-4 my-4 flex items-center justify-between">
        <h1>My carbon asset</h1>
        <div className="flex justify-between gap-2">
          <Button>refresh</Button>
          <Button>Start bridging</Button>
        </div>
      </div>
      <Table />
      <Table />
      <Table />
    </>
  )
}

export default Home

{
  /* <div className="mx-4 my-4 flex flex-col gap-4 ">
<div className="mx-4 my-4 flex items-center justify-between">
  <h1>My carbon asset</h1>
  <div className="flex gap-2">
    <Button
      intent="outlined"
      onClick={() => {
        void refetch({
          throwOnError: true,
          cancelRefetch: true,
        });
      }}
    >
      refresh
    </Button>
    <Button
      className="p-0"
      intent="contained"
      onClick={() => {
        void showModal();
      }}
    >
      <TbBuildingBridge className="mr-2 h-6 w-6" />
      <span className="text-sm">start bridging</span>
    </Button>
  </div>
</div>
<Asset title="Nft batches" loading={isFetching || isLoading} columns={columns} defaultData={Rows}></Asset>
<Asset title="Tokens" loading={true}></Asset>
<Asset title="Pools tokens"></Asset>
</div> */
}
